-- PURGE existing data for test load
SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE OrderDeliveryAddress;
TRUNCATE TABLE OrderToItems;
TRUNCATE TABLE Orders;
TRUNCATE TABLE RestaurantToMenu;
TRUNCATE TABLE RestaurantToHours;
TRUNCATE TABLE Hours;
TRUNCATE TABLE MenuItems;
TRUNCATE TABLE Restaurant;
TRUNCATE TABLE Address;
TRUNCATE TABLE Staff;
TRUNCATE TABLE LoginCredentials;
TRUNCATE TABLE Driver;
SET FOREIGN_KEY_CHECKS=1;
INSERT INTO Address(streetAddress1, city, state, zip) VALUES ('234 Lake Street','Boston','MA','02132');
SET @addr := LAST_INSERT_ID();
INSERT INTO Restaurant(restName,addressID,contactName,contactEmail,contactPhone,isActive,approvalByAdminStatus,pendingWithdraw) VALUES ('All Chicken Meals',@addr,'Laura Wimbleton','?????????','617-478-3785','Y','Approved','N');
INSERT INTO Address(streetAddress1, city, state, zip) VALUES ('719 Hobatt Road','Chestnut Hill','MA','02129');
SET @addr := LAST_INSERT_ID();
INSERT INTO Restaurant(restName,addressID,contactName,contactEmail,contactPhone,isActive,approvalByAdminStatus,pendingWithdraw) VALUES ('Pizza Only',@addr,'Russel Beverton','?????????','857-477-2773','Y','Approved','N');
INSERT INTO Address(streetAddress1, city, state, zip) VALUES ('28093 Park Avenue','Newton Corner','MA','02125');
SET @addr := LAST_INSERT_ID();
INSERT INTO Restaurant(restName,addressID,contactName,contactEmail,contactPhone,isActive,approvalByAdminStatus,pendingWithdraw) VALUES ('Best Burgers',@addr,'Eager Alloysis','?????????','781-467-0073','Y','Approved','N');
INSERT INTO Hours(dayOfWeek, openTime, closeTime, isClosed) VALUES ('Mon','09:00:00','21:00:00','N');
SET @hid := LAST_INSERT_ID();
INSERT INTO RestaurantToHours(restName,hoursID) VALUES ('All Chicken Meals',@hid);
INSERT INTO Hours(dayOfWeek, openTime, closeTime, isClosed) VALUES ('Tue','09:00:00','21:00:00','N');
SET @hid := LAST_INSERT_ID();
INSERT INTO RestaurantToHours(restName,hoursID) VALUES ('All Chicken Meals',@hid);
INSERT INTO Hours(dayOfWeek, openTime, closeTime, isClosed) VALUES ('Wed','09:00:00','21:00:00','N');
SET @hid := LAST_INSERT_ID();
INSERT INTO RestaurantToHours(restName,hoursID) VALUES ('All Chicken Meals',@hid);
INSERT INTO Hours(dayOfWeek, openTime, closeTime, isClosed) VALUES ('Thu','09:00:00','21:00:00','N');
SET @hid := LAST_INSERT_ID();
INSERT INTO RestaurantToHours(restName,hoursID) VALUES ('All Chicken Meals',@hid);
INSERT INTO Hours(dayOfWeek, openTime, closeTime, isClosed) VALUES ('Fri','09:00:00','21:00:00','N');
SET @hid := LAST_INSERT_ID();
INSERT INTO RestaurantToHours(restName,hoursID) VALUES ('All Chicken Meals',@hid);
INSERT INTO Hours(dayOfWeek, openTime, closeTime, isClosed) VALUES ('Sat','08:00:00','22:00:00','N');
SET @hid := LAST_INSERT_ID();
INSERT INTO RestaurantToHours(restName,hoursID) VALUES ('All Chicken Meals',@hid);
INSERT INTO Hours(dayOfWeek, openTime, closeTime, isClosed) VALUES ('Sun','08:00:00','22:00:00','N');
SET @hid := LAST_INSERT_ID();
INSERT INTO RestaurantToHours(restName,hoursID) VALUES ('All Chicken Meals',@hid);
INSERT INTO Hours(dayOfWeek, openTime, closeTime, isClosed) VALUES ('Mon','09:00:00','00:00:00','N');
SET @hid := LAST_INSERT_ID();
INSERT INTO RestaurantToHours(restName,hoursID) VALUES ('Pizza Only',@hid);
INSERT INTO Hours(dayOfWeek, openTime, closeTime, isClosed) VALUES ('Tue','09:00:00','00:00:00','N');
SET @hid := LAST_INSERT_ID();
INSERT INTO RestaurantToHours(restName,hoursID) VALUES ('Pizza Only',@hid);
INSERT INTO Hours(dayOfWeek, openTime, closeTime, isClosed) VALUES ('Wed','09:00:00','00:00:00','N');
SET @hid := LAST_INSERT_ID();
INSERT INTO RestaurantToHours(restName,hoursID) VALUES ('Pizza Only',@hid);
INSERT INTO Hours(dayOfWeek, openTime, closeTime, isClosed) VALUES ('Thu','09:00:00','00:00:00','N');
SET @hid := LAST_INSERT_ID();
INSERT INTO RestaurantToHours(restName,hoursID) VALUES ('Pizza Only',@hid);
INSERT INTO Hours(dayOfWeek, openTime, closeTime, isClosed) VALUES ('Fri','00:00:00','00:00:00','Y');
SET @hid := LAST_INSERT_ID();
INSERT INTO RestaurantToHours(restName,hoursID) VALUES ('Pizza Only',@hid);
INSERT INTO Hours(dayOfWeek, openTime, closeTime, isClosed) VALUES ('Sat','10:00:00','00:00:00','N');
SET @hid := LAST_INSERT_ID();
INSERT INTO RestaurantToHours(restName,hoursID) VALUES ('Pizza Only',@hid);
INSERT INTO Hours(dayOfWeek, openTime, closeTime, isClosed) VALUES ('Sun','10:00:00','00:00:00','N');
SET @hid := LAST_INSERT_ID();
INSERT INTO RestaurantToHours(restName,hoursID) VALUES ('Pizza Only',@hid);
INSERT INTO Hours(dayOfWeek, openTime, closeTime, isClosed) VALUES ('Mon','09:00:00','00:00:00','N');
SET @hid := LAST_INSERT_ID();
INSERT INTO RestaurantToHours(restName,hoursID) VALUES ('Best Burgers',@hid);
INSERT INTO Hours(dayOfWeek, openTime, closeTime, isClosed) VALUES ('Tue','09:00:00','00:00:00','N');
SET @hid := LAST_INSERT_ID();
INSERT INTO RestaurantToHours(restName,hoursID) VALUES ('Best Burgers',@hid);
INSERT INTO Hours(dayOfWeek, openTime, closeTime, isClosed) VALUES ('Wed','09:00:00','00:00:00','N');
SET @hid := LAST_INSERT_ID();
INSERT INTO RestaurantToHours(restName,hoursID) VALUES ('Best Burgers',@hid);
INSERT INTO Hours(dayOfWeek, openTime, closeTime, isClosed) VALUES ('Thu','09:00:00','00:00:00','N');
SET @hid := LAST_INSERT_ID();
INSERT INTO RestaurantToHours(restName,hoursID) VALUES ('Best Burgers',@hid);
INSERT INTO Hours(dayOfWeek, openTime, closeTime, isClosed) VALUES ('Fri','09:00:00','00:00:00','N');
SET @hid := LAST_INSERT_ID();
INSERT INTO RestaurantToHours(restName,hoursID) VALUES ('Best Burgers',@hid);
INSERT INTO Hours(dayOfWeek, openTime, closeTime, isClosed) VALUES ('Sat','00:00:00','00:00:00','Y');
SET @hid := LAST_INSERT_ID();
INSERT INTO RestaurantToHours(restName,hoursID) VALUES ('Best Burgers',@hid);
INSERT INTO Hours(dayOfWeek, openTime, closeTime, isClosed) VALUES ('Sun','00:00:00','00:00:00','Y');
SET @hid := LAST_INSERT_ID();
INSERT INTO RestaurantToHours(restName,hoursID) VALUES ('Best Burgers',@hid);
INSERT INTO MenuItems(itemName,itemDescription,itemPrice,isAvailable) VALUES ('Nuggets','', 5.99, 'Y');
SET @mid := LAST_INSERT_ID();
INSERT INTO RestaurantToMenu(restName,itemID) VALUES ('All Chicken Meals',@mid);
INSERT INTO MenuItems(itemName,itemDescription,itemPrice,isAvailable) VALUES ('Wings','', 10.99, 'N');
SET @mid := LAST_INSERT_ID();
INSERT INTO RestaurantToMenu(restName,itemID) VALUES ('All Chicken Meals',@mid);
INSERT INTO MenuItems(itemName,itemDescription,itemPrice,isAvailable) VALUES ('Combo','', 23.99, 'N');
SET @mid := LAST_INSERT_ID();
INSERT INTO RestaurantToMenu(restName,itemID) VALUES ('All Chicken Meals',@mid);
INSERT INTO MenuItems(itemName,itemDescription,itemPrice,isAvailable) VALUES ('Sandwich','', 8.99, 'N');
SET @mid := LAST_INSERT_ID();
INSERT INTO RestaurantToMenu(restName,itemID) VALUES ('All Chicken Meals',@mid);
INSERT INTO MenuItems(itemName,itemDescription,itemPrice,isAvailable) VALUES ('Wrap','', 6.99, 'N');
SET @mid := LAST_INSERT_ID();
INSERT INTO RestaurantToMenu(restName,itemID) VALUES ('All Chicken Meals',@mid);
INSERT INTO MenuItems(itemName,itemDescription,itemPrice,isAvailable) VALUES ('Pepperoni(Small)','', 12.99, 'Y');
SET @mid := LAST_INSERT_ID();
INSERT INTO RestaurantToMenu(restName,itemID) VALUES ('Pizza Only',@mid);
INSERT INTO MenuItems(itemName,itemDescription,itemPrice,isAvailable) VALUES ('Pepperoni(Large)','', 17.99, 'N');
SET @mid := LAST_INSERT_ID();
INSERT INTO RestaurantToMenu(restName,itemID) VALUES ('Pizza Only',@mid);
INSERT INTO MenuItems(itemName,itemDescription,itemPrice,isAvailable) VALUES ('Supreme','', 21.99, 'N');
SET @mid := LAST_INSERT_ID();
INSERT INTO RestaurantToMenu(restName,itemID) VALUES ('Pizza Only',@mid);
INSERT INTO MenuItems(itemName,itemDescription,itemPrice,isAvailable) VALUES ('Hawaiian','', 24.99, 'N');
SET @mid := LAST_INSERT_ID();
INSERT INTO RestaurantToMenu(restName,itemID) VALUES ('Pizza Only',@mid);
INSERT INTO MenuItems(itemName,itemDescription,itemPrice,isAvailable) VALUES ('Your 3 topping','', 15.99, 'N');
SET @mid := LAST_INSERT_ID();
INSERT INTO RestaurantToMenu(restName,itemID) VALUES ('Pizza Only',@mid);
INSERT INTO MenuItems(itemName,itemDescription,itemPrice,isAvailable) VALUES ('Butter burger','', 9.99, 'Y');
SET @mid := LAST_INSERT_ID();
INSERT INTO RestaurantToMenu(restName,itemID) VALUES ('Best Burgers',@mid);
INSERT INTO MenuItems(itemName,itemDescription,itemPrice,isAvailable) VALUES ('Cheese Burger','', 5.99, 'N');
SET @mid := LAST_INSERT_ID();
INSERT INTO RestaurantToMenu(restName,itemID) VALUES ('Best Burgers',@mid);
INSERT INTO MenuItems(itemName,itemDescription,itemPrice,isAvailable) VALUES ('Hamburger','', 4.99, 'N');
SET @mid := LAST_INSERT_ID();
INSERT INTO RestaurantToMenu(restName,itemID) VALUES ('Best Burgers',@mid);
INSERT INTO MenuItems(itemName,itemDescription,itemPrice,isAvailable) VALUES ('BBSpecial','', 12.99, 'N');
SET @mid := LAST_INSERT_ID();
INSERT INTO RestaurantToMenu(restName,itemID) VALUES ('Best Burgers',@mid);
INSERT INTO MenuItems(itemName,itemDescription,itemPrice,isAvailable) VALUES ('BBDouble','', 11.99, 'N');
SET @mid := LAST_INSERT_ID();
INSERT INTO RestaurantToMenu(restName,itemID) VALUES ('Best Burgers',@mid);
INSERT INTO LoginCredentials(username,password,userType) VALUES ('richard01','pw','Staff');
INSERT INTO Staff(username, firstName, lastName, employementStatus) VALUES ('richard01','Amanda','Richard','Active');
INSERT INTO LoginCredentials(username,password,userType) VALUES ('cox02','pw','Staff');
INSERT INTO Staff(username, firstName, lastName, employementStatus) VALUES ('cox02','Arthur','Cox','Active');
INSERT INTO LoginCredentials(username,password,userType) VALUES ('deckon03','pw','Staff');
INSERT INTO Staff(username, firstName, lastName, employementStatus) VALUES ('deckon03','Charles','Deckon','Active');
INSERT INTO LoginCredentials(username,password,userType) VALUES ('cox04','pw','Staff');
INSERT INTO Staff(username, firstName, lastName, employementStatus) VALUES ('cox04','Francis','Cox','Active');
INSERT INTO LoginCredentials(username,password,userType) VALUES ('mullard05','pw','Staff');
INSERT INTO Staff(username, firstName, lastName, employementStatus) VALUES ('mullard05','Sarah','Mullard','Active');
-- Restaurant owners (login)
INSERT INTO LoginCredentials(username,password,userType) VALUES ('owner_chicken','pw','Restaurant');
INSERT INTO LoginCredentials(username,password,userType) VALUES ('owner_pizza','pw','Restaurant');
INSERT INTO LoginCredentials(username,password,userType) VALUES ('owner_burger','pw','Restaurant');
INSERT INTO Driver(driverName, employementStatus, isAvailable) VALUES ('Shawn  Murray','Active','Open');
INSERT INTO Driver(driverName, employementStatus, isAvailable) VALUES ('Alex Shopper','Active','Open');
INSERT INTO Driver(driverName, employementStatus, isAvailable) VALUES ('Lisa  Graham','Inactive','Open');
INSERT INTO Driver(driverName, employementStatus, isAvailable) VALUES ('Ryan Graham','Active','Open');
INSERT INTO Driver(driverName, employementStatus, isAvailable) VALUES ('Marcus  Shane','Active','Open');
INSERT INTO Driver(driverName, employementStatus, isAvailable) VALUES ('Vicky  Kissinger','Active','Open');
INSERT INTO Driver(driverName, employementStatus, isAvailable) VALUES ('Lucy Gordon','Inactive','Open');
-- Sample orders based on restaurants
SET @nowdate := CURDATE(); SET @nowtime := CURTIME();
-- Additional staff accounts
INSERT INTO LoginCredentials(username,password,userType) VALUES ('mollie21','temp-pw','Staff');
INSERT INTO Staff(username, firstName, lastName, employementStatus) VALUES ('mollie21','Mollie','Demo','Active');
INSERT INTO LoginCredentials(username,password,userType) VALUES ('ruby34','temp-pw','Staff');
INSERT INTO Staff(username, firstName, lastName, employementStatus) VALUES ('ruby34','Ruby','Demo','Active');
INSERT INTO LoginCredentials(username,password,userType) VALUES ('luke77','temp-pw','Staff');
INSERT INTO Staff(username, firstName, lastName, employementStatus) VALUES ('luke77','Luke','Demo','Active');
