services:
  db:
    image: mysql:8.0
    container_name: frontdash_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: asdf1234gfuyiofyudfcjfikyu
      MYSQL_DATABASE: frontdash
      MYSQL_USER: frontdash_user
      MYSQL_PASSWORD: frontdash_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  mysql_data: